// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.29.1
// source: service/service.proto

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClipboardService_Read_FullMethodName  = "/cpserv.server.ClipboardService/Read"
	ClipboardService_Write_FullMethodName = "/cpserv.server.ClipboardService/Write"
)

// ClipboardServiceClient is the client API for ClipboardService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClipboardServiceClient interface {
	Read(ctx context.Context, in *Auth, opts ...grpc.CallOption) (*Clipboard, error)
	Write(ctx context.Context, in *WriteReq, opts ...grpc.CallOption) (*Empty, error)
}

type clipboardServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClipboardServiceClient(cc grpc.ClientConnInterface) ClipboardServiceClient {
	return &clipboardServiceClient{cc}
}

func (c *clipboardServiceClient) Read(ctx context.Context, in *Auth, opts ...grpc.CallOption) (*Clipboard, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Clipboard)
	err := c.cc.Invoke(ctx, ClipboardService_Read_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clipboardServiceClient) Write(ctx context.Context, in *WriteReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ClipboardService_Write_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClipboardServiceServer is the server API for ClipboardService service.
// All implementations must embed UnimplementedClipboardServiceServer
// for forward compatibility.
type ClipboardServiceServer interface {
	Read(context.Context, *Auth) (*Clipboard, error)
	Write(context.Context, *WriteReq) (*Empty, error)
	mustEmbedUnimplementedClipboardServiceServer()
}

// UnimplementedClipboardServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClipboardServiceServer struct{}

func (UnimplementedClipboardServiceServer) Read(context.Context, *Auth) (*Clipboard, error) {
	return nil, status.Error(codes.Unimplemented, "method Read not implemented")
}
func (UnimplementedClipboardServiceServer) Write(context.Context, *WriteReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Write not implemented")
}
func (UnimplementedClipboardServiceServer) mustEmbedUnimplementedClipboardServiceServer() {}
func (UnimplementedClipboardServiceServer) testEmbeddedByValue()                          {}

// UnsafeClipboardServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClipboardServiceServer will
// result in compilation errors.
type UnsafeClipboardServiceServer interface {
	mustEmbedUnimplementedClipboardServiceServer()
}

func RegisterClipboardServiceServer(s grpc.ServiceRegistrar, srv ClipboardServiceServer) {
	// If the following call panics, it indicates UnimplementedClipboardServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClipboardService_ServiceDesc, srv)
}

func _ClipboardService_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Auth)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClipboardServiceServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClipboardService_Read_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClipboardServiceServer).Read(ctx, req.(*Auth))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClipboardService_Write_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClipboardServiceServer).Write(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClipboardService_Write_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClipboardServiceServer).Write(ctx, req.(*WriteReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ClipboardService_ServiceDesc is the grpc.ServiceDesc for ClipboardService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClipboardService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cpserv.server.ClipboardService",
	HandlerType: (*ClipboardServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Read",
			Handler:    _ClipboardService_Read_Handler,
		},
		{
			MethodName: "Write",
			Handler:    _ClipboardService_Write_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service/service.proto",
}
